package com.suburbscore.suburb.enums;

public enum SydneyRegion {
    INNER_CITY,
    EASTERN_SUBURBS,
    INNER_WEST,
    NORTH_SHORE_RYDE,
    NORTHERN_BEACHES,
    THE_HILLS_DISTRICT,
    WESTERN_SYDNEY,
    SOUTH_WESTERN_SYDNEY,
    MACARTHUR,
    SUTHERLAND_ST_GEORGE,
    BLUE_MOUNTAINS,
    HAWKESBURY,
    CENTRAL_COAST,

    // NSW Regions
    HUNTER_NEWCASTLE,
    NEW_ENGLAND,
    MID_NORTH_COAST,
    NORTH_COAST,
    ILLAWARRA,
    SOUTH_COAST,
    SOUTHERN_HIGHLANDS_GOULBURN,
    SNOWY_MONARO,
    RIVERINA,
    CENTRAL_WEST,

    OTHER_NSW  // ACT postcodes (2600-2618) + anything unmatched
}
